name: Build & Publish

on:
  push:
    branches: ["develop" ]
  pull_request:
    branches: [ "master" ,"ci"]

env:
  PROJECT_PATH: 'src/Doppler.Extensions.Configuration/Doppler.Extensions.Configuration.csproj'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ${{env.PROJECT_PATH}}
      
    - name: Build
      run: dotnet build ${{env.PROJECT_PATH}} --no-restore --configuration Release  
      
    - name: Publish Doppler.Extensions.Configuration
      uses: alirezanet/publish-nuget@v3.0.0
      with:
          PROJECT_FILE_PATH: ${{env.PROJECT_PATH}}
          VERSION_FILE_PATH: src/Directory.Build.props
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: true
